introduction: |-
    > Node.js idiomatic client for [Kubernetes Engine][product-docs] cluster management.

    [Kubernetes Engine](https://cloud.google.com/kubernetes-engine/docs/) is used for
    building and managing container based applications, powered by the open source Kubernetes technology.